### ISSUE TITLE
Can't build R18.1 with SSL - OS-X El Capitan

### ISSUE THREAD

**Issue by binarytemple** [yrashk/kerl#103]
I've previously built the following OTP with SSL support (required by [rebar]() )

```
r15b01
r15b02
r15b03
r16b03
r17.0
```

But for some reason when I try to build R18.1 - AFAIK using the same ~/.kerlrc and build method - it now fails to build with SSL support. 

```
[/basho/meck%]. /erls/r18.1/activate
[/basho/meck%]erl -eval "crypto:start(), halt()." -noshel
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V7.1  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{crypto,start,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},
{line,669}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]},{init,start_em,1,[]
}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
```
I've got the following `~/.kerlrc` and I even tried `source ~/.kerlrc` before running the usual build and install commands:

```
kerl build 18.1 R18.1  
kerl install R18.1 /erls/r18.1
```

```
export KERL_CONFIGURE_OPTIONS="--disable-hipe --enable-smp-support --enable-threads --enable-kernel-poll --
enable-darwin-64bit"
export CFLAGS="-DOPENSSL_NO_EC=1"
```
I've deleted the `~/.kerl` directory and repeated the steps but it just doesn't seem to be including 'crypto'. 

Can anyone suggest something else I could try, desperate to get R18 built and activated.

**Comment by binarytemple** [comment]
# Problem solved 

Issue was that the nice recent version of openssl supplied with brew was not being used - OpenSSL 0.9.8zg 14 July 2015 - supplied by OSX was being used instead.

Solution :

    brew link --force openssl

An alternative suggested solution was to use `--with-ssl=/usr/local` - but that didn't work. 

Hope this is of help to someone.

**Comment by stavro** [comment]
Thank you @binarytemple for posting your solution! This worked.

**Comment by binarytemple** [comment]
No problem always happy to help. B                                                                                                                                                                                                                                                                                                                                                                                                                    From: Sean StavropoulosSent: Thursday, January 7, 2016 5:56 AMTo: yrashk/kerlReply To: yrashk/kerlCc: Bryan HuntSubject: Re: [kerl] Can't build R18.1 with SSL - OS-X El Capitan (#103)Thank you @binarytemple for posting your solution! This worked.

—Reply to this email directly or view it on GitHub.

**Comment by kesslerm** [comment]
Another solution that works for me is to add `--with-ssl=/usr/local/opt/openssl` to `KERL_CONFIGURE_OPTIONS` in `~/.kerlrc`. The homebrew-installed openssl version is found there including the actual openssl tools (which are not in the standard `/usr/local/*` path unless overriden with by `brew link --force openssl`). Use this approach if you want to keep the OS X provided openssl tools as defaults.

Tested with 18.2.1 and R16B02-basho9

**Comment by binarytemple** [comment]
Nice tip @kesslerm - suspect the Erlang build scripts need to get a little smarter.
