### ISSUE TITLE
Can't build on OSX

### ISSUE THREAD

**Issue by msilvestre** [yrashk/kerl#109]
On Mac OSX El Captain (10.11.3)

When I try to build erlang it always fails with errors.

I've tried with version 17.5 (the one I'm actually interested) and with 18.0.

$kerl build 17.5 17.5
Verifying archive checksum...
Checksum verified (346dd0136bf1cc28cebc140e505206bb)
Building Erlang/OTP 17.5 (17.5), please wait...

Build failed, see /Users/miguel.silvestre/.kerl/builds/17.5/otp_build_17.5.log

Checking the log it has the following errors:
MPT-00770:~ miguel.silvestre$ vi /Users/miguel.silvestre/.kerl/builds/17.5/otp_build_17.5.log

 MAKE   depend
 MAKE   generate
 GEN    x86_64-apple-darwin15.3.0/gen_git_version.mk
 GEN    x86_64-apple-darwin15.3.0/erl_version.h
 GEN    x86_64-apple-darwin15.3.0/opt/plain/GENERATED
 MAKE   depend
 GEN    x86_64-apple-darwin15.3.0/opt/plain/depend.mk
 MAKE   depend
make[4]: Nothing to be done for `depend'.
 GEN    x86_64-apple-darwin15.3.0/gen_git_version.mk
 GEN    x86_64-apple-darwin15.3.0/gen_git_version.mk
make[2]: Nothing to be done for `depend'.
 MAKE   depend
make[2]: Nothing to be done for `depend'.
 MAKE   emulator
 MAKE   opt
 GEN    x86_64-apple-darwin15.3.0/opt/smp/GENERATED
 GEN    x86_64-apple-darwin15.3.0/opt/smp/depend.mk
 MAKE   depend
make[5]: Nothing to be done for `depend'.
 GEN    x86_64-apple-darwin15.3.0/gen_git_version.mk
 GEN    x86_64-apple-darwin15.3.0/gen_git_version.mk
 CC     obj/x86_64-apple-darwin15.3.0/opt/smp/erl_main.o
error: unable to open output file 'obj/x86_64-apple-darwin15.3.0/opt/smp/erl_main.o': ''
1 error generated.
make[3]: *** [obj/x86_64-apple-darwin15.3.0/opt/smp/erl_main.o] Error 1
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

Any clues?

Thanks

**Comment by mrallen1** [comment]
Can you provide more information about your compilation environment? Are you using Apple's clang compiler or gcc from homebrew? Are you sure you have permission to write into this directory or have enough disk space?

**Comment by msilvestre** [comment]
Sorry, This was really a noob problem. For some reason OSX removed my access rights to the directory,
