### ISSUE TITLE
status, prompt, active - these commands don't work with old installations

### ISSUE THREAD

**Issue by s1n4** [yrashk/kerl#69]
After updating my clone of kerl I noticed that kerl status, prompt and active commands no longer work but only with old installations.

This is the cause: https://github.com/spawngrid/kerl/commit/9cf83c965f2318421f0f68c6328958ea0d846e48#diff-75743bad0452412b658dabebd6b439f4R653
so now what one should do to make it work with old installations (those installations that are made before the commit I mentioned above) is appending the following to the _activate_ file of each installation
```shell
_KERL_ACTIVE_DIR="/path/to/otp-installation"
export _KERL_ACTIVE_DIR
```

**Comment by mrallen1** [comment]
I am going to close this issue because it's been >2 years since the commit in question.
