### ISSUE TITLE
Can't delete builds 

### ISSUE THREAD

**Issue by binarytemple** [yrashk/kerl#72]
I'm using kerl installed from homebrew on OSX, brew takes it from master. 

    %kerl list builds
    R16B03-1,r16b03-1
    %kerl delete build r16b03-1
    No build named r16b03-1
    %kerl delete build  R16B03-1
    No build named  R16B03-1

On my other machine, I've resorted to deleting the ~/.kerl directory, but that's kinda clunky. 
Same old story, I built Erlang for 32 bit OS, need to delete.

**Comment by mrallen1** [comment]
Clean up still is broken but looks like #75 fixes this particular issue. Going to open a new issue for cleanup.
