### ISSUE TITLE
What is the role of kerl in Erlang version management?

### ISSUE THREAD

**Issue by Stratus3D** [yrashk/kerl#80]
Is kerl intended to manage Erlang versions? It makes it easy to install different versions of Erlang easy but management of versions is hard. For example suppose I have Erlang 16 and Erlang 17 installed. To use Erlang 17 I must run `. ~/.kerl/builds/17.1/release_17.1/activate`. Then I can use Erlang 17 in the current session. If I start another session and what to use the same version of Erlang I must run the same command again. 

Is kerl meant to be used to manage Erlang versions? Or is there another piece of software used for switching between Erlang versions that I should be using?

If kerl is meant to be used for management of Erlang versions I see many ways in which it can be improved (for example, it could be updated so `kerl activate 17.1` could be run instead of `. ~/.kerl/builds/17.1/release_17.1/activate`). I would happy to create a PR that adds this functionality to kerl.

**Comment by rlipscombe** [comment]
fwiw, I use direnv to switch Erlang versions.

**Comment by Stratus3D** [comment]
I now use [asdf](https://github.com/asdf-vm/asdf) to manage Erlang versions during development.
