### ISSUE TITLE
Install via binary packages

### ISSUE THREAD

**Issue by BanzaiMan** [yrashk/kerl#82]
Right now, `kerl` compiles each Erlang runtime from source when `kerl build` and `kerl install` are called. This is a rather time-consuming process, and this makes harder and harder to support multiple versions of Erlang on Travis CI.

Tremendous amount of time will be saved if `kerl` can install from [binary packages offered by Erlang Solutions](https://www.erlang-solutions.com/downloads/download-erlang-otp). (Ubuntu packages are of most interest to Travis CI.) Some binary packages are not conducive to side-by-side installations, but some hacks may be possible.

**Comment by sanmiguel** [comment]
Hi @BanzaiMan ! It sounds like this might have ended with you finding a different solution?

From a purely selfish point-of-view, is there anything we can do to help expedite getting erlang releases available on Travis-CI sooner after they are released? Right now 18.3 is out, but I don't think it's available yet on build hosts.

**Comment by BanzaiMan** [comment]
@sanmiguel We are now building OTP releases with https://github.com/travis-ci/travis-erlang-builder. The release process is manual, however, so we still have to kick off the build in order to make a new release available.

**Comment by BanzaiMan** [comment]
This issue, on the other hand, seems to have run its course, so I'm closing this.
