### ISSUE TITLE
activete kerl paramete on FreeBSD 10.1

### ISSUE THREAD

**Issue by poi119** [yrashk/kerl#93]
I try to use ( .  -> dot command) on ubuntu 12.04 ,it's work fine ,but on target platform on my project is
FreeBSD 10.1 Dot commad(.) didn't work, Pls help me for provide solution on active parameter on kerl on  activate it:
$ . /path/to/install/dir/activate - ubuntu

**Comment by radekg** [comment]
What's your shell? . (source) should work with bash. Are you using sh on FreeBSD 10.1?

**Comment by poi119** [comment]
i used sh shell , i solve bu down grade to freebsd 9.3 and used "su login" then used activate parameter.

**Comment by radekg** [comment]
Just use bash.

**Comment by poi119** [comment]
bash shell ,It's work too, thank for answer!
